### ISSUE TITLE
关于MITS的请教

### ISSUE THREAD

**Issue by YangBo0411** [yoxu515/MITS#6]
作者您好，对您的工作很感兴趣，有几个问题想向您请教一下。
1、MITS是能够以bounding box的标注形式经过网络训练直接输出mask和bounding box的预测结果吗？反之，mask的标注形式也是一样的。
2、如果我有一个数据集有mask和bounding box两种标注形式，MITS能够以两种标注标注形式来训练网络吗？
3、MITS如果以两种标注形式来训练网络，最终的预测效果是否比运用单一的标注形式性能更优。

**Comment by skdream3d** [comment]
你好，MITS支持bouding box和mask两种混合数据的训练。
i）数据中有一部分有mask，有一部分有box，放在一起训练，mask用来监督mask的分支，box用来监督box的分支。ii）数据中都有mask，这时mask的bounding box可以用来监督box的分支。iii）数据中只有box，这种情况MITS是不支持的。
首先如果数据量更多的话，模型的泛化性会得到提升，在更大的domain上会更稳定。其次数据中有更多mask的话会让预测效果得到提升，因为mask是让模型实现精细跟踪的关键。

**Comment by yoxu515** [comment]
你好，MITS支持bouding box和mask两种混合数据的训练。
i）数据中有一部分有mask，有一部分有box，放在一起训练，mask用来监督mask的分支，box用来监督box的分支。ii）数据中都有mask，这时mask的bounding box可以用来监督box的分支。iii）数据中只有box，这种情况MITS是不支持的。
首先如果数据量更多的话，模型的泛化性会得到提升，在更大的domain上会更稳定。其次数据中有更多mask的话会让预测效果得到提升，因为mask是让模型实现精细跟踪的关键。

**Comment by YangBo0411** [comment]
好的，明白了，感谢您的及时回复 。
